apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
# base64("cronpilot") = Y3JvbnBpbG90
data:
  POSTGRES_DB: Y3JvbnBpbG90
  POSTGRES_USER: Y3JvbnBpbG90
  POSTGRES_PASSWORD: Y3JvbnBpbG90
