apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kafka-demo

resources:
  - ../../../base/kafka-producer
  - namespace.yaml

images:
  - name: kafka-producer
    newTag: latest
