apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cronpilot
  namespace: argocd
spec:
  description: Project for all CronPilot playground applications
  sourceRepos:
  - https://github.com/irwanseptian/irwandhi-gitops-lab.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: cronpilot-api
  - server: https://kubernetes.default.svc
    namespace: cronpilot-frontend
  - server: https://kubernetes.default.svc
    namespace: cronpilot-worker
  - server: https://kubernetes.default.svc
    namespace: cron-webhook
  - server: https://kubernetes.default.svc
    namespace: postgres
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: Project for all infra playground applications
  sourceRepos:
  - https://github.com/irwanseptian/irwandhi-gitops-lab.git
  destinations:
  - server: https://kubernetes.default.svc
    namespace: argocd
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
