name              = "dev"
subnet_id         = "subnet-068bdcc4eb63d329a"
security_group_id = "sg-093bd0e8c0955881b"
key_name          = "cronpilot"
instance_name     = "cronpilot-vm"
aws_region        = "ap-southeast-1"
