apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronpilot-api
  namespace: argocd
spec:
  project: cronpilot
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/cronpilot-api
  destination:
    server: https://kubernetes.default.svc
    namespace: cronpilot-api
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronpilot-frontend
  namespace: argocd
spec:
  project: cronpilot
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/cronpilot-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: cronpilot-frontend
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cronpilot-worker
  namespace: argocd
spec:
  project: cronpilot
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/cronpilot-worker
  destination:
    server: https://kubernetes.default.svc
    namespace: cronpilot-worker
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cron-webhook
  namespace: argocd
spec:
  project: cronpilot
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/cron-webhook
  destination:
    server: https://kubernetes.default.svc
    namespace: cron-webhook
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: infra/argocd/overlays/playground
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/keda
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-producer
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/kafka-producer
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-producer
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-consumer
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/kafka-consumer
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-consumer
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/irwanseptian/irwandhi-gitops-lab.git
    targetRevision: HEAD
    path: kubernetes/overlays/playground/logging
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
